// agent-bootstrap is the program that an AI agent (Claude Code, Copilot, etc.)
// generates when scaffolding a new application. It provisions the full
// infrastructure stack and writes connection strings to .env — all in one
// idempotent pass.
//
// The agent runs this file once during project initialisation. Subsequent runs
// skip provisioning if the .env file already contains valid tokens.
//
// Usage (generated by agent):
//
//	go run examples/agent-bootstrap/main.go
package main

import (
	"bufio"
	"context"
	"fmt"
	"log"
	"os"
	"strings"

	"github.com/InstaNode-dev/sdk-go/instant"
)

const envFile = ".env"

// envVars maps .env keys to their description.
// The agent writes these on first run; the developer checks them in (or into
// their secret manager).
var envVars = map[string]string{
	"DATABASE_URL":    "",
	"REDIS_URL":       "",
	"NATS_URL":        "",
	"INSTANT_API_KEY": "", // filled by user after claiming
}

func main() {
	ctx := context.Background()

	// Load existing .env so we can skip already-provisioned resources.
	existing := loadDotEnv(envFile)

	client := instant.New()

	fmt.Println("instant.dev agent-bootstrap: provisioning project infrastructure...")
	fmt.Println()

	updates := map[string]string{}

	// --- Postgres ---
	if existing["DATABASE_URL"] == "" {
		fmt.Print("  Provisioning Postgres... ")
		db, err := client.ProvisionDatabase(ctx, &instant.ProvisionOpts{Name: "app-db"})
		if err != nil {
			log.Fatalf("postgres: %v", err)
		}
		updates["DATABASE_URL"] = db.ConnectionURL
		fmt.Printf("OK  (%s tier, %d MB)\n", db.Tier, db.Limits.StorageMB)
		if db.Note != "" {
			fmt.Println("     Note:", db.Note)
		}
	} else {
		fmt.Println("  Postgres: already provisioned, skipping.")
	}

	// --- Redis ---
	if existing["REDIS_URL"] == "" {
		fmt.Print("  Provisioning Redis...    ")
		cache, err := client.ProvisionCache(ctx, &instant.ProvisionOpts{Name: "app-cache"})
		if err != nil {
			log.Fatalf("redis: %v", err)
		}
		val := cache.ConnectionURL
		if cache.KeyPrefix != "" {
			// Embed the key prefix as a comment for developer awareness.
			val = cache.ConnectionURL + "  # key prefix: " + cache.KeyPrefix
		}
		updates["REDIS_URL"] = val
		fmt.Printf("OK  (%s tier, %d MB)\n", cache.Tier, cache.Limits.MemoryMB)
	} else {
		fmt.Println("  Redis:    already provisioned, skipping.")
	}

	// --- NATS Queue ---
	if existing["NATS_URL"] == "" {
		fmt.Print("  Provisioning NATS...     ")
		q, err := client.ProvisionQueue(ctx, &instant.ProvisionOpts{Name: "app-queue"})
		if err != nil {
			log.Fatalf("nats: %v", err)
		}
		updates["NATS_URL"] = q.ConnectionURL
		fmt.Printf("OK  (%s tier, %d MB)\n", q.Tier, q.Limits.StorageMB)
	} else {
		fmt.Println("  NATS:     already provisioned, skipping.")
	}

	// Write new values to .env
	if len(updates) > 0 {
		if err := writeDotEnv(envFile, existing, updates); err != nil {
			log.Fatalf("write .env: %v", err)
		}
		fmt.Println()
		fmt.Printf("Wrote %d new values to %s\n", len(updates), envFile)
	}

	fmt.Println()
	fmt.Println("Bootstrap complete.")
	fmt.Println()
	fmt.Println("Next steps:")
	fmt.Println("  1. Load .env in your app (e.g. github.com/joho/godotenv)")
	fmt.Println("  2. Claim your resources permanently: https://instant.dev/start")
	fmt.Println("  3. Set INSTANT_API_KEY in your secret manager after claiming.")
}

// loadDotEnv reads a .env file and returns a map of key=value pairs.
// Missing file is treated as empty (not an error).
func loadDotEnv(path string) map[string]string {
	out := make(map[string]string)
	f, err := os.Open(path) //nolint:gosec
	if err != nil {
		return out // file doesn't exist yet
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			key := strings.TrimSpace(parts[0])
			val := strings.TrimSpace(parts[1])
			out[key] = val
		}
	}
	return out
}

// writeDotEnv merges existing and new values and writes them back to path.
func writeDotEnv(path string, existing, updates map[string]string) error {
	merged := make(map[string]string, len(existing)+len(updates))
	for k, v := range existing {
		merged[k] = v
	}
	for k, v := range updates {
		merged[k] = v
	}

	// Preserve a predictable key order for readability.
	order := []string{
		"DATABASE_URL",
		"REDIS_URL",
		"NATS_URL",
		"INSTANT_API_KEY",
	}
	// Append any extra keys that weren't in the expected list.
	inOrder := make(map[string]bool)
	for _, k := range order {
		inOrder[k] = true
	}
	for k := range merged {
		if !inOrder[k] {
			order = append(order, k)
		}
	}

	var sb strings.Builder
	sb.WriteString("# Generated by instant.dev agent-bootstrap — do not edit manually.\n")
	sb.WriteString("# Claim at https://instant.dev to make resources permanent.\n\n")
	for _, k := range order {
		v, ok := merged[k]
		if !ok || v == "" {
			continue
		}
		sb.WriteString(k + "=" + v + "\n")
	}

	return os.WriteFile(path, []byte(sb.String()), 0600)
}
