// agent-bootstrap is the program that an AI agent (Claude Code, Copilot, etc.)
// generates when scaffolding a new application. It provisions the full
// infrastructure stack and writes connection strings to .env — all in one
// idempotent pass.
//
// The agent runs this file once during project initialisation. Subsequent runs
// skip provisioning if the .env file already contains valid tokens.
//
// Usage (generated by agent):
//
//	go run examples/agent-bootstrap/main.go
package main

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"log"
	"os"
	"strings"

	"github.com/InstaNode-dev/sdk-go/instant"
)

const envFile = ".env"

func main() {
	ctx := context.Background()
	client := instant.New()
	if err := Run(ctx, client, envFile, os.Stdout); err != nil {
		log.Fatal(err)
	}
}

// Run executes the bootstrap flow against client, reading + writing path as
// the .env file and emitting progress to out. It is extracted from main() so
// the example is covered by the package's tests without spinning up a real
// network: tests pass an httptest-backed *instant.Client, a temp-dir .env
// path, and io.Discard.
//
// Behaviour matches the agent contract:
//  1. Load existing .env (missing file is treated as empty).
//  2. For each missing key (DATABASE_URL / REDIS_URL / NATS_URL), provision
//     the corresponding resource and record the connection URL.
//  3. Write the merged values back to .env in a stable, predictable order.
//
// Run returns the first provisioning error encountered.
func Run(ctx context.Context, client *instant.Client, path string, out io.Writer) error {
	existing := loadDotEnv(path)

	fmt.Fprintln(out, "instant.dev agent-bootstrap: provisioning project infrastructure...")
	fmt.Fprintln(out)

	updates := map[string]string{}

	// --- Postgres ---
	if existing["DATABASE_URL"] == "" {
		fmt.Fprint(out, "  Provisioning Postgres... ")
		db, err := client.ProvisionDatabase(ctx, &instant.ProvisionOpts{Name: "app-db"})
		if err != nil {
			return fmt.Errorf("postgres: %w", err)
		}
		updates["DATABASE_URL"] = db.ConnectionURL
		fmt.Fprintf(out, "OK  (%s tier, %d MB)\n", db.Tier, db.Limits.StorageMB)
		if db.Note != "" {
			fmt.Fprintln(out, "     Note:", db.Note)
		}
	} else {
		fmt.Fprintln(out, "  Postgres: already provisioned, skipping.")
	}

	// --- Redis ---
	if existing["REDIS_URL"] == "" {
		fmt.Fprint(out, "  Provisioning Redis...    ")
		cache, err := client.ProvisionCache(ctx, &instant.ProvisionOpts{Name: "app-cache"})
		if err != nil {
			return fmt.Errorf("redis: %w", err)
		}
		val := cache.ConnectionURL
		if cache.KeyPrefix != "" {
			// Embed the key prefix as a comment for developer awareness.
			val = cache.ConnectionURL + "  # key prefix: " + cache.KeyPrefix
		}
		updates["REDIS_URL"] = val
		fmt.Fprintf(out, "OK  (%s tier, %d MB)\n", cache.Tier, cache.Limits.MemoryMB)
	} else {
		fmt.Fprintln(out, "  Redis:    already provisioned, skipping.")
	}

	// --- NATS Queue ---
	if existing["NATS_URL"] == "" {
		fmt.Fprint(out, "  Provisioning NATS...     ")
		q, err := client.ProvisionQueue(ctx, &instant.ProvisionOpts{Name: "app-queue"})
		if err != nil {
			return fmt.Errorf("nats: %w", err)
		}
		updates["NATS_URL"] = q.ConnectionURL
		fmt.Fprintf(out, "OK  (%s tier, %d MB)\n", q.Tier, q.Limits.StorageMB)
	} else {
		fmt.Fprintln(out, "  NATS:     already provisioned, skipping.")
	}

	// Write new values to .env
	if len(updates) > 0 {
		if err := writeDotEnv(path, existing, updates); err != nil {
			return fmt.Errorf("write .env: %w", err)
		}
		fmt.Fprintln(out)
		fmt.Fprintf(out, "Wrote %d new values to %s\n", len(updates), path)
	}

	fmt.Fprintln(out)
	fmt.Fprintln(out, "Bootstrap complete.")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "Next steps:")
	fmt.Fprintln(out, "  1. Load .env in your app (e.g. github.com/joho/godotenv)")
	fmt.Fprintln(out, "  2. Claim your resources permanently: https://instant.dev/start")
	fmt.Fprintln(out, "  3. Set INSTANT_API_KEY in your secret manager after claiming.")

	return nil
}

// loadDotEnv reads a .env file and returns a map of key=value pairs.
// Missing file is treated as empty (not an error).
func loadDotEnv(path string) map[string]string {
	out := make(map[string]string)
	f, err := os.Open(path) //nolint:gosec
	if err != nil {
		return out // file doesn't exist yet
	}
	defer func() { _ = f.Close() }()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			key := strings.TrimSpace(parts[0])
			val := strings.TrimSpace(parts[1])
			out[key] = val
		}
	}
	return out
}

// writeDotEnv merges existing and new values and writes them back to path.
func writeDotEnv(path string, existing, updates map[string]string) error {
	merged := make(map[string]string, len(existing)+len(updates))
	for k, v := range existing {
		merged[k] = v
	}
	for k, v := range updates {
		merged[k] = v
	}

	// Preserve a predictable key order for readability.
	order := []string{
		"DATABASE_URL",
		"REDIS_URL",
		"NATS_URL",
		"INSTANT_API_KEY",
	}
	// Append any extra keys that weren't in the expected list.
	inOrder := make(map[string]bool)
	for _, k := range order {
		inOrder[k] = true
	}
	for k := range merged {
		if !inOrder[k] {
			order = append(order, k)
		}
	}

	var sb strings.Builder
	sb.WriteString("# Generated by instant.dev agent-bootstrap — do not edit manually.\n")
	sb.WriteString("# Claim at https://instant.dev to make resources permanent.\n\n")
	for _, k := range order {
		v, ok := merged[k]
		if !ok || v == "" {
			continue
		}
		sb.WriteString(k + "=" + v + "\n")
	}

	return os.WriteFile(path, []byte(sb.String()), 0600)
}
